### ISSUE TITLE
Setup Travis for Continuous Integration

### ISSUE THREAD

**Issue by yawboakye** [devcongress/jobs#10]
[Travis](https://travis-ci.org) is available for free to open source projects. It will be a good idea to set it up for the project to run against current Ruby and Rails versions as well as their heads so that we know when is a good time to upgrade. Ideally we should be on the latest versions of both.

**Comment by schalkneethling** [comment]
@yawboakye Are there specific tests or a build you want to run? Do you want to run on pull requests or, only when merging to master?

**Comment by yawboakye** [comment]
@schalkneethling I don't have any preference here but if I had to choose I'd prefer run on PR as it could give more confidence about the code to the reviewer.

**Comment by yawboakye** [comment]
@schalkneethling `bin/rails test`

**Comment by colinwarmstrong** [comment]
I configured Travis CI and put in Pull Request #15.  I was able to successfully push and build through Travis CI on my branch.  There is a test that occasionally fail which could affect future Travis CI builds.
