### ISSUE TITLE
Industry options not loading

### ISSUE THREAD

**Issue by claudey** [devcongress/jobs#269]
On the company creation page, there's supposed to be a dropdown from which the user selects which industry the new company belongs to. The industry list is loaded from a .csv gist file. This feature was initially introduced and worked in [this PR.](https://github.com/devcongress/jobs/pull/29)

In the latest update, the dropdown no longer appears, and this seems to prevent the register button from working.

An acceptable PR should have the dropdown populated with the industry list, as before.

**Comment by silentworks** [comment]
This doesn't seem to be missing, maybe its just missing from the UI code. The seed code is still in place.

https://github.com/devcongress/jobs/blob/master/db/seeds.rb#L12-L17
