### ISSUE TITLE
Show Company website as link

### ISSUE THREAD

**Issue by claudey** [devcongress/jobs#55]
When a user views a company page, that page currently has information about the company. Some of this information is the company website.

Currently the website is just shown as text. Show this website text as link so please can click to go to the company website. More kudos when the website opens in another tab.

**Comment by yawboakye** [comment]
@claudey Not something I'm attached to but apparently, opening a new link in a new tab is not as easy as `target="_blank"`. I think it should be fine to use the same tab for this navigation. The user has the choice of using the browser's built-in function to open in a new tab, or go back to the previous page in case they just clicked on the link.

**Comment by claudey** [comment]
That's fine. 👍

**Comment by yawboakye** [comment]
Resolved!
