### ISSUE TITLE
Redirect to Home page after Sign up

### ISSUE THREAD

**Issue by claudey** [devcongress/jobs#58]
Currently, there's no "Admin dashboard". When users sign up, it currently redirects them to create a company.

To resolve this issue, please redirect a user to the home page after they have successfully signed up.

**Comment by claeusdev** [comment]
@claudey SIgn up redirected me to the homepage

**Comment by yawboakye** [comment]
@claudey I set it up to be that way. I thought the only people who needed to sign up where recruiters that's why I redirected them to immediately create the company they want to recruit for. Why do you not like it this way?

**Comment by claudey** [comment]
@yawboakye Can't believe I didn't even think about this. Now that you've explained, that makes sense. Thanks.
