### ISSUE TITLE
Show signed-in Users an Add Company link

### ISSUE THREAD

**Issue by claudey** [devcongress/jobs#61]
For anyone to add a job, they have to do so under a new company. Currently the link to add a company is not stated, so people are not easily able to do so.

On the nav bar, add a link `Add Company` to the links so that it only shows to signed in users.

**Comment by yawboakye** [comment]
@claeusdev @claudey They should be redirected to the create company page first, and after they've done that they can create the job post. Due to the infrequency of adding companies, I suggest we put the link in their profile page instead?

**Comment by claudey** [comment]
@yawboakye You make sense, and you're right about the infrequency. On the other hand,  they don't have a profile page now so it's not quite intuitive how they can create a new company. Once they have a profile page, it'll be a good place to have that link appear.
