### ISSUE TITLE
Better formatting for Text area fields

### ISSUE THREAD

**Issue by claudey** [devcongress/jobs#67]
There are several fields in the app which are of input type `textarea`. Per basic rails formatting, they have no styling which means job owners can not add lists, bullets, etc.

Rails 6 will be shipping with `actiontext` which adds some styling to text areas, but we'd like to give it an early try.

Implement [rails/actiontext](https://rubygems.org/gems/actiontext) on the app so that people can format, in rich text, content for text areas.

**Comment by claeusdev** [comment]
@claudey actiontext requires Ruby >= 2.5.0 but our current ruby is 2.3.3, COuld it still work?
