### ISSUE TITLE
New password can not be saved

### ISSUE THREAD

**Issue by claudey** [devcongress/jobs#68]
In #66, it was noted that there's a process for generating a link to get a new password. When the person clicks on the `change my password` link, they're redirected to a page where they can set a new password.

After the new password has been entered, submitting the form on the page returns an error. It'll be best if the password is reset, and they are redirected to the login page to continue their use.

**Comment by claudey** [comment]
@yawboakye, please take a look at this, and help tackle it.

**Comment by yawboakye** [comment]
@claudey Fixed! But I'd be happy if I didn't have to attend to further issues related to Devise. As you know, I'm not their biggest fan.
