### ISSUE TITLE
Company setup should have a logo field

### ISSUE THREAD

**Issue by silentworks** [devcongress/jobs#73]
We should allow for a company to provide a logo when signing up.

**Comment by yawboakye** [comment]
@silentworks @claudey Who to upload the images to?

**Comment by yawboakye** [comment]
We can begin by asking for the URL to the logo. If they have a website they could have their logo on there and should be able to use the same link here. But that's not a good long term solution.

**Comment by bubunyo** [comment]
We used to do this with AF Radio, these guys deleted the images and we were left with dead images. Just Saying.

**Comment by seanmavley** [comment]
as per the scenario @bubunyo mentioned, then I'm imagining if the image doesn't exist, a placeholder of sorts can be loaded instead

**Comment by bubunyo** [comment]
I think cloudinary is a good option

**Comment by yawboakye** [comment]
@bubunyo Sure, I was thinking of what would be the cheapest option in the interim. If we can go with them.

**Comment by bubunyo** [comment]
I think it should suffice for about a year. And i am sure by the time we
have more than enough traffic there will be a way it will pay for itself so
we can move it to s3 of gcloud

**Comment by claudey** [comment]
@bubunyo I'm guessing, per @seanmavley's suggestion, we can have an image like this to use, when they don't supply a logo url, an image like this loads from our `images` directory. That way we can delay cloudinary et al for some time.

<img width="369" alt="screenshot 2019-02-28 at 4 38 35 pm" src="https://user-images.githubusercontent.com/1866816/53582431-61d4e500-3b77-11e9-86fb-c22c7813121b.png">

@yawboakye @silentworks thoughts?

**Comment by bubunyo** [comment]
Makes sense to me.

**Comment by claudey** [comment]
Resolved in ebc4518ad85387920189fac565f6b55eb0f44b7d
